### ISSUE TITLE
Feature clarification - dry and wet inputs on ch1 and 2?

### ISSUE THREAD

**Issue by colmoni** [lack/soundcraft-utils#33]
This is a question about existing functionality, as I don't yet own a Notepad but am interested.

On the 2 channel Notepad mixers, does your utility have the ability to route a dry signal on ch1, and mix on ch2?

I don't believe this functionality exists in Windows or Mac, so wouldn't be surprised if it's not possible on Linux. Only the 12FX can feed both dry (ch1+2) and wet (mix L/R via ch3+4) signal on separate USB channels simultaneously, according to manufacturer documentation.

**Comment by ndim** [comment]
As far as I am aware and as far as I can tell, the audio routing always happens to a pair of channels.

In the case of the Notepad-5, our code has these four options:

```
    Label = {
        Sources.MONO_1_MONO_2: ("Mic/Line 1", "Mono Line 2"),
        Sources.STEREO_2_3: stereo_label("Stereo 2/3"),
        Sources.STEREO_4_5: stereo_label("Stereo 4/5"),
        Sources.MASTER_L_R: stereo_label("Mix"),
    }
```

and in the case of the Notepad-8FX,

```
    Label = {
        Sources.INPUT_1_2: ("Mic/Line 1", "Mic/Line 2"),
        Sources.INPUT_3_4: stereo_label("Stereo 3/4"),
        Sources.INPUT_5_6: stereo_label("Stereo 5/6"),
        Sources.MASTER_L_R: stereo_label("Mix"),
    }
```

However, with the Notepad-8FX, you could use the following workaround:

  * set channel 2 AUX/FX and LEVEL pots to -∞
  * set channel 2 gain to unity
  * set AUX MASTER to unity
  * plug a TS or TRS patch cable between the AUX out and channel 2 line input (both balanced TRS or unbalanced TS should be fine)
  * have the software set audio routing from input channel 1+2 ("INPUT_1_2" in our code) to the stereo USB audio device

Now that I think about it... you could probably do the same thing with the Notepad-5's MONITOR pots instead of AUX pots, and MONITOR out instead of AUX out.

This is slightly adapted from my workaround for doing a mono mix minus with the Notepad-12FX: Input to channel 2 is the mono mix minus from AUX, and then route the stereo Mix to the USB device 3+4 alongside the always-on input channels 1+2 being on USB device 1+2.

Note that with both the 8FX and the 12FX, the effects unit can only be added to the MASTER mix, not to the AUX signal which we have patched to channel 2 for recording with the cable.

So if you were to go this route, your purchasing alternative in Soundcraft Notepad world would be

  * Notepad-5 + cable
  * Notepad-8FX + cable
  * Notepad-12FX without cable

which shrinks the price difference between the 8FX and the 12FX's by the price of one cable, if space and power consumption and wast heat are not a concern.

Of course, the cable trick works independent of the operating system.

HTH, otherwise please clarify.

**Comment by colmoni** [comment]
I did consider using a physical patch cable to route output to input. I'd be nervous about accidentally creating a feedback loop! Nevertheless, this goes well beyond the bounds of what you can do in software and has been most helpful, thank you.

I think the reason these devices aren't more popular as an alternative to much less fully featured interfaces is their complexity. For the cost difference, the 12FX seems well worth it. There's a myriad of use cases. There isn't a massive software bundle but then Linux users can't use those anyway!

**Comment by ndim** [comment]
Well, people's use cases differ wildly, and once you depart from a simple consumer hifi receiver concept of "select one of these inputs", a world of possibilities and thus complexity opens, and people need to take on a bit more responsibility for their actions in exchange for getting more possibilities.

It's a bit like a cordless drill and a circular saw. You can build a whole lot more specialized desks and tables with those than you can buy at Ikea, but you do need to be careful about your fingers and toes when cutting and assembling.

As to the software to use for recording or live, I cannot say much: I have not really used any recording software yet.

A few remarks on the Notepad-12FX, which is the only mixer I actually own besides my old Behringer Xenyx 302USB, but of which I only use a fraction of its feature set:

  * The 4x4 USB interface's 4 channel input and 4 channel output devices are usually interpreted as 4 channel surround sound interfaces by at least parts of the software stack, which can be a bit weird.
  * I have not researched further about splitting those two 4 channel devices into two 2 channel devices. I have read that pipewire is supposed to do that better than pulseaudio and/or jack to, but have no actual experience with that. I hope I can eventually solve this using pipewire.
  * The USB output 3+4 can only be routed to the headphone out jack, so your only options to use the USB output 3+4 channels are to either
      * listen to a software mix with the headphones
      * use a TRS to two TS patch cable to patch the USB3+4 from the headphone out to one of the Stereo IN (or FX RTN) channel pairs (I have tried this as a proof of concept, but never actually used it for an actual application)
  * Normal Linux software stereo out works without special device setup on pulseaudio and pipewire. The stereo sound is routinely routed to the 4 channel USB output device channels 1+2 without issues. That is what my normal music software player, youtube video sound, etc. goes through.
  * Ardour and/or jack seemed to be able to record from the 4 channel USB input as two stereo channels IIRC the one time I tried it out, but I never got around to actually using the 12FX for actually recording anything.
  * I have not had an opportunity yet to find out whether e.g. mumble can be used well with the 12-FX: If I connect the condenser mic to MIC channel 2, there is no stereo signal on USB input device 1+2 with channel 1 being silent, and I do not know whether I can tell e.g. mumble to just use a mono mic signal from USB input device channel 2, and if I put the stereo mix onto USB input device channels 3+4 via software setup, I do not know whether I can tell e.g. mumble to use channels 3+4.

Yes, complexity. Still, much less complex than designing and soldering my own mixer circuit, and implementing firmware for it.

My usual use case for the Notepad-12FX is to sum up a few stereo sources into a stereo signel: a guitar preamp in ST 5+6, a BT receiver in ST 7+8 (mixers with builtin BT are much more expensive, and usually have USB-in and BT-in in the same channel strip), youtube/vlc/etc. in ST 9+10, and headphone out to headphones or MASTER out to my hifi amp + stereo speakers. Very rarely do I plug the guitar into CH 1 or 3 directly, or a condenser mic into CH 2 or 4. So the USB input device is not really used here at all.

BTW, it is very well possible that the Notepad hardware supports routing a dry signal to one channel and a mono mix to the other channel and it is just the Notepad firmware (and Windows/MacOS setup software) which limit the available settings to always route the audio in channel pairs: The added user interface complexity of splitting stereo signals would certainly be a challenge.

Anyway, it is possible other devices have become available since I bought my 12FX in August of 2020, but I have not researched the market for this class of devices since I bought the 12FX.

**Comment by colmoni** [comment]
I appreciate the complexity analogy, that's the experience of most Linux users! If you break it, it's your own fault...

My use case is entirely different (and demonstrative of how versatile this device is), anything from one to four mics to record or stream speech, either digital to a PC or analogue to an external recorder (or audio interface, though that's rather redundant). I use Carla patchbay for live processing, Ardour for recording (it shows up in Carla).

My understanding of Jack is the 12FX will show up as four capture channels and two output (the only stereo device I have are headphones). Plugins in Carla can be mono or stereo, but routing stereo is a matter of linking L and R channel outputs separately.

**Comment by lack** [comment]
I use Jack with my 12FX, and it shows up as 4 captures and 4 outputs, letting you route your audio separately to each one.

I personally have a guitar line-in to ch1, mic to ch2, stereo keyboard to 5/6, with the input mapping configured so that the keyboard inputs are capture 3/4.  These go into non-mixer for tighter control over the incoming mix that goes into pulse-in so my mic (and optionally guitar and keyboard) can be routed easily into pulse-in where it gets routed into zoom calls.  Fun for sound effects during meetings!

When recording, I route the inputs manually into ardour tracks.

I have my pulse-output from the computer attached to both output 1/2 (which comes out in the mixer as input 9/10, so you can adjust that  relative to the other inputs that go to the master R/L of the mixer).  But I also have the same pulse-output L/R attached to output 3/4.  The reason I do that is it lets me have 2 mixes; one is the Master L/R from the instruments, with or without the USB audio via the 9/10 mixer knob; the other is just the USB audio and nothing else.  This is nice when the kids want to bang on the keyboard while I'm on a work call.  I can turn down the USB to the mains so they don't hear the meeting, and I don't hear the keyboard in my headphones!

**Comment by ndim** [comment]
> My understanding of Jack is the 12FX will show up as four capture channels and two output (the only stereo device I have are headphones). Plugins in Carla can be mono or stereo, but routing stereo is a matter of linking L and R channel outputs separately.

Almost. The 12FX shows up as one 4 channel capture device and one 4 channel playback device ("4x4 USB"):

  * capture device channels 1+2 are always mixer channels 1+2, pre-fader.
  * capture device channels 3+4 are what can be set to either of the options using e.g. `soundcraft-utils`
  * playback device channels 1+2 are normal stereo out and appear in the 9/10 partial channel strip (only AUX, PAN, and LEVEL are available, while TRIM/GAIN and EQ are missing)
  * The headphone jack will either play the stereo MASTER mix (with its overall level set by the headphone volume pot) or playback device channels 3+4

**Comment by lack** [comment]
Oh, and another neat feature of the 12FX that lends itself to more mixing opportunities is the AUX line.  You can use that for a 3rd independent mix, either to headphones or mono line out.  Again, this is a combination of all inputs post-fader with USB 1&2 coming is as line 9/10.

I currently use this as a line-out to my keyboard's vocoder input.  Just need to remember to keep the keyboard's AUX at -∞ or face the feedback.

**Comment by ndim** [comment]
And when you are using the AUX out as headphone out, that signal even is in stereo (the parts taken from the mixer's stereo input channels). It is pre-PAN, though, so the mixer's mono channels sit dead center in the AUX-as-headphones stereo image.

This feature should not be exclusive for the Notepad-12FX, though: The Notepad-8FX also appears to have it under the same name, and even the Notepad-5 appears to be capable of doing the same with its MONITOR instead of AUX.

FYI, you cannot route AUX to the USB capture device inside the 8FX or 12FX, but the patch cable workaround only works with the 12FX, not with the 8FX if you want to record both the stereo AUX mix and something else.

For the patch cable workaround, you need a patch cable (unbal TRS stereo to two unbal TS mono) to patch it to an unused stereo channel and route that to USB capture device channels 3+4, or patch it onto mixer channels 1+2 (and set channel 1+2 GAIN+EQ pots to the same value) to have the stereo AUX mix available as USB capture device channels 1+2, and e.g. the MASTER mix as USB capture device channels 3+4.

For more features and/or flexibility, expect to start looking at several times the price of the Soundcraft Notepad-12FX. Then you are in the land of linear faders (nice feel, but not for channel-to-AUX, and takes lots of space) and many more channels on the USB audio devices. The devices where I would start my research with my limited market knowledge from reading datasheets and browsing favourite dealer's webshop would be the Soundcraft Signature 12MTK (14x12 USB at 24bit and 48kHz max) and Presonus AR8c/AR12c/AR16c (8x4, 14x4, 18x4 USB at 24bit and 96kHz max). The Yamaha MG series appear to be very nice mixers with a high quality USB interface (192kHz, 24bit), but that is only 2x2 channels and appears to be locked to recording the mix.

**Comment by lack** [comment]
It looks like the question was answered!
